// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('hello-world')['HelloWorld']
    ImageCard: typeof import('./src/components/ImageCard.vue')['default']
    MyComponent: typeof import('./src/components/MyComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}

export {}
